[customizations.installer.kickstart]
contents = """
%post
bootc switch --mutate-in-place --transport registry ghcr.io/mecattaf/harness:latest
%end
"""

[customizations.installer.modules]
enable = ["Storage", "Runtime", "Network", "Security", "Services", "Users", "Timezone"]
disable = ["Subscription"]
